language: python

python:
  - '2.7'

env: 
  global:
    - PYTEST="bin/py.test -n 2 -vvs"

  matrix:
    - TEST_SUITE="$PYTEST"
    - TEST_SUITE="./etc/release/release.sh"

install:
  - ./configure

script:
  - $TEST_SUITE

notifications:
  irc:
    channels:
      - "chat.freenode.net#aboutcode"
  on_sucess: change
  on_failure: always
  use_notice: true
  skip_join: true
  template:
    - "%{repository_slug}#%{build_number} (%{branch}-%{commit}:%{author})-%{message}- %{build_url}"
